config/routes.rb
Rails.application.routes.draw do
  root 'users#index'

  get 'users/search' => 'users#search'

  post 'users/status' => 'users#status'

  devise_for :users

  resources :users, only: [:edit, :show, :update]

  resources :friendships

end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
	belongs_to :user

	# def self.is_friend?(user_id, friend_id)
	# 	return Friendship.exists?(friend_id: friend_id, user_id: user_id)
	# end

end

app/models/status.rb
class Status < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :friendships
  has_many :statuses

  def friend_statuses()
  
  	friend_hash = Hash.new
  	friend_array = friendships
  	friend_array.each do |f|
      friend_name = "#{f.user.first_name} #{f.user.last_name}"
      friend_statuses = f.user.statuses
      friend_hash.store(friend_name, friend_statuses)
  	end
    user_full_name = "#{first_name} #{last_name}"
    friend_hash.store(user_full_name, statuses)
  	return friend_hash
  end

end

# <% if current_user.id != user.id %>
#     <% if @friendship.new_record? %>
#       <%= form_for @friendship do |f| %>
#         <%= f.hidden_field :friend_id, value: user.id %>
#         <%= f.submit("Add Friend") %>
#       <% end %>
#     <% else %>
#       <%= form_tag(friendship_path(@friendship.id), method: "delete") do %>
#         <%= submit_tag("Remove Friend") %>
#       <% end %>
#     <% end %>
#   <% end %>

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:first_name, :last_name, :birthday, :location]
  end

end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
	before_action :authenticate_user!

	def create
		@new_friend = Friendship.create( user_id: current_user.id,
      		friend_id: params[:friendship][:friend_id])
     	redirect_to root_path
	end

	def destroy
	    friendship_object = Friendship.find(params[:id])
	    friendship_object.destroy
    	redirect_to root_path
	end

	def update
		#update database to show friend request is accepted
    @friend = Friendship.find(params[:id])
    @friend.update(accepted: true,
      pending: false)
    user_id = @friend.user_id
    friend_id = @friend.friend_id
    Friendship.create(user_id: friend_id,
    	friend_id: user_id,
    	accepted: true,
    	pending: false)
    redirect_to user_path(@friend.friend_id)
    #add row in database reflecting that they are your friend also
    # @friend_to_current = Friendship.new(user_id: current_user.id, 
    #   friend_id: @friend.user_id,
    #   accepted: true,
    #   pending: false)
    # @friend_to_current.save
    # redirect_to users_friend_requests_path

    # @friend = Friendship.find(params[:friendship_id])
    # @friend.update(pending: false)
    # redirect_to users_friend_requests_path
	end

	def index
		@friendships = Friendship.where(friend_id: current_user.id, pending: true)

	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @status = current_user.friend_statuses()
    @user = current_user
    @new_status = Status.new
  end

  def new
  end

  def create
  end

  def show
    @user = User.find(params[:id])
    @statuses = @user.statuses
    @friendships = Friendship.where(friend_id: current_user.id, accepted: true)
    @friendship = current_user.friendships.find_by(friend_id: @user.id) || Friendship.new
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    @user.update(first_name: params[:user][:first_name],
      last_name: params[:user][:last_name],
      birthday: params[:user][:birthday],
      location: params[:user][:location],
      email: params[:user][:email])

    redirect_to @user
  end

  # def friends_add
  #   @new_friend = Friendship.create( user_id: current_user.id,
  #     friend_id: params[:friend_id])
  #   redirect_to 'search'
  # end

  # def friends_remove
  #   friendship_object = Friendship.where(user_id: current_user.id, friend_id: params[:friend_id])
  #   Friendship.destroy(friendship_object.id)
  #   render 'search'
  # end

  def status
    @new_status = Status.new(status: params[:status_entered],
      user_id: current_user.id)
    @new_status.save
    
    redirect_to root_path

  end

  def search
    @list = User.where('first_name LIKE :search OR last_name LIKE :search', search: "%#{params[:search]}%")

  end


  # def accept_friend_request
  #   #update database to show friend request is accepted
  #   @friend = Friendship.find(params[:friendship_id])
  #   @friend.update(accepted: true,
  #     pending: false)
  #   #add row in database reflecting that they are your friend also
  #   @friend_to_current = Friendship.new(user_id: current_user.id, 
  #     friend_id: @friend.user_id,
  #     accepted: true,
  #     pending: false)
  #   @friend_to_current.save
  #   redirect_to users_friend_requests_path
  # end

  # def reject_friend_request
  #   @friend = Friendship.find(params[:friendship_id])
  #   @friend.update(pending: false)
  #   redirect_to users_friend_requests_path

  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/friendships/index.html.erb
<% @friendships.each do |request| %>
	<p><%= "#{request.user.first_name} #{request.user.last_name}" %></p>
	<p><%= request.user.location %></p>
	<%= form_tag(friendship_path(request.id), method: "put") do %>
		<%= submit_tag "Accept Request" %>
	<% end %>
	<%= form_tag(friendship_path(request.id), method: "delete") do %>
		<%= submit_tag "Reject Request" %>
	<% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bewd19FinalProjectEasolom</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	
<% if user_signed_in? %>
    <p><%= link_to "Sign out", destroy_user_session_path, method: :delete %> | 
    	<%= link_to "Edit User", edit_user_registration_path %></p>
    <p>
    	<%= link_to "Home Feed", root_path %> |
    	<%= link_to "Profile", user_path(current_user.id) %> |
    	<%= link_to "Search", users_search_path %> |
    	<%= link_to "Friend Requests", friendships_path %>
    </p>
<% else %>
    <%= link_to "Sign up", new_user_registration_path %> | <%= link_to "Sign in", new_user_session_path %>
<% end %>

<%= yield %>

</body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<%= form_for @user do |f| %>
	<p>
	<%= f.label :first_name %>
	<%= f.text_field :first_name %>
	</p>
	
	<p>
	<%= f.label :last_name %>
	<%= f.text_field :last_name %>
	</p>
	
	<p>
	<%= f.label :birthday %>
	<%= f.date_field :birthday %>
	</p>
	
	<p>
	<%= f.label :location %>
	<%= f.text_field :location %>
	</p>

	<p>
	<%= f.label :email %>
	<%= f.text_field :email %>
	</p>

	<p>
	<%= f.submit %>
	</p>
<% end %>

app/views/users/index.html.erb
<% if @new_status.errors.any? %>
	<h2>There were errors saving your status </h2>
	<ul>
		<% @new_status.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
	</ul>
<% end %>



<div class="profile">
	<h1><%= "#{@user.first_name} #{@user.last_name}" %></h1>
	<p><%= "#{@user.email}" %></p>
	<p><%= "#{@user.birthday}" %></p>
	<p><%= "#{@user.location}" %></p>
</div>

<div class="button"><%= link_to "Edit Profile", edit_user_path(current_user.id) %></div>

<%= form_tag("/users/status", method: "post") do %>
	<%= label_tag(:status_entered, "Enter a new status here") %>
	<%= text_field_tag(:status_entered) %>
	<%= submit_tag("Post Status") %>
<% end %>


<% @status.each do |key, status_array| %>
	<% status_array.each do |status| %>
		<p class="statuses"><%= "#{key}: #{status.status}" %></p>
	<% end %>
<% end %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/search.html.erb
<%= form_tag "/users/search", method: "GET" do |f| %>
	<%= label_tag(:search, "Search for:") %>
	<%= text_field_tag(:search, params[:search]) %>
	<%= submit_tag("Search") %>
<% end %>

<% @list.each do |user| %>
	<div class="profile">
		<h4><%= link_to "#{user.first_name} #{user.last_name}", user_path(user.id) %></h4>
		<p><%= "#{user.email}" %></p>
		<p><%= "#{user.birthday}" %></p>
		<p><%= "#{user.location}" %></p>
	</div>
	
<% end %>

app/views/users/show.html.erb
<div class="profile">
	<h1><%= "#{@user.first_name} #{@user.last_name}" %></h1>
	<p><%= "#{@user.email}" %></p>
	<p><%= "#{@user.birthday}" %></p>
	<p><%= "#{@user.location}" %></p>
</div>
<% if current_user.id != @user.id %>
	<% if @friendship.new_record? %>
		<%= form_for @friendship do |f| %>
			<%= f.hidden_field :friend_id, value: @user.id %>
			<%= f.submit("Add Friend") %>
		<% end %>
	<% else %>
		<%= form_tag(friendship_path(@friendship.id), method: "delete") do %>
			<%= submit_tag("Remove Friend") %>
		<% end %>
	<% end %>
<% end %>

<div class ="statuses">
	<h3>A list of Statuses</h3>
	<% @statuses.each do |s| %>
		<div class="statuses">
			<p><%= s.status %></p>
			<p><%= s.created_at %></p>
		</div>
	<% end %>
</div>

<div class="friends">
	<h3>Friends</h3>
	<% @friendships.each do |friendship| %>
		<div>
			<p><%= link_to friendship.user.first_name, user_path(friendship.user) %></p>
			<p><%= friendship.user.location %>></p>
			<% friendship.user.statuses.each do |i| %>
				<p><%= i.status %></p>
			<% end %>
		</div>
	<% end %>
</div>